<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Default.aspx.cs" Inherits="Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>无标题页</title>
</head>
<body BGCOLOR=#FFFFFF LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0>
    <form id="form1" runat="server">
    <div>
<TABLE WIDTH=770 BORDER=0 CELLPADDING=0 CELLSPACING=0 align="center">
	<TR>
		<TD COLSPAN=3 style="height: 19px">
			</TD>
	</TR>
	<TR>
		<TD COLSPAN=3 style="background-color: #9ea29e; font-size: 12px; color: white;" height="20px">
            <table cellspacing="0">
                <tr>
                    <td style="width: 806px; height: 18px;">
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<asp:Button
                            ID="Button1" runat="server" OnClick="Button1_Click" Text="安全退出" />
                        &nbsp; &nbsp;
                        <asp:Label ID="Label1" runat="server"
                Text="Label"></asp:Label>&nbsp;</td>
                    <td align="right" style="width: 650px; height: 18px;">
                        当前日期：<asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    </td>
                </tr>
            </table>
        </TD>
	</TR>
	
	<TR>
		<TD valign="top" background="images/default_6.gif" style="height: 16px; width: 139px;">
			<IMG SRC="images/default_3.gif"  ></TD>
		<TD ROWSPAN=2 HEIGHT=653 valign="top" style="width: 477px; background-image: url(images/default_5.gif);">			<iframe style="height: 768px; width: 864px;" frameborder="0" height="640" name="main" scrolling="" src="main.aspx" width="586">
        </iframe>
        </TD>

	</TR>
	<TR>
		<TD valign="top" background="images/default_6.gif" align="left" style="width: 139px; height: 500px; font-size: small;">
            <asp:TreeView ID="TreeView1" runat="server" Font-Size="Small" Width="139px" AutoGenerateDataBindings="False" EnableTheming="True" ExpandDepth="0">
                <Nodes>
                
                    <asp:TreeNode Text="初始化" Value="初始化">
                        <asp:TreeNode Text="运动会基本信息" Value="运动会基本信息" NavigateUrl="~/work/ini1.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="参赛规程设定" Value="参赛规程设定" NavigateUrl="~/work/ini7.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode NavigateUrl="~/work/ini4.aspx" Target="main" Text="参赛项目设置" Value="参赛项目设置">
                        </asp:TreeNode>
                        <asp:TreeNode NavigateUrl="~/work/ini5.aspx" Target="main" Text="可选项目管理" Value="可选项目管理">
                        </asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="报名表" Value="报名表">
                        <asp:TreeNode Text="参赛队报名" Value="参赛队报名" NavigateUrl="~/work/ini3.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode NavigateUrl="~/work/bianpaimanage/manage2.aspx" Target="main" Text="报名表项目顺序"
                            Value="报名表项目顺序"></asp:TreeNode>
                        <asp:TreeNode Text="生成报名表" Value="生成报名表" NavigateUrl="~/work/ini8.aspx" Target="main">
                         
                        </asp:TreeNode>
                        <asp:TreeNode Text="导入报名表" Value="导入报名表" NavigateUrl="~/work/ini9.aspx" Target="main"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="查询统计" Value="查询统计">
                        <asp:TreeNode Text="参赛规程查询" Value="参赛规程查询" NavigateUrl="~/work/search/search1.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="运动员情况统计" Value="运动员情况统计" Target="main" NavigateUrl="~/work/search/search0.aspx"></asp:TreeNode>
                        <asp:TreeNode Text="参赛项目统计" Value="参赛项目统计" NavigateUrl="~/work/search/search4.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="参赛队基本信息统计" Value="参赛队基本信息统计" Target="main" NavigateUrl="~/work/search/search5.aspx"></asp:TreeNode>
                        <asp:TreeNode Text="运动员参赛情况统计" Value="运动员参赛情况统计" Target="main" NavigateUrl="~/work/search/search6.aspx"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="编排管理" Value="编排管理">
                        <asp:TreeNode Text="竞赛日程安排" Value="竞赛日程安排" NavigateUrl="~/work/bianpaimanage/manage1.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode NavigateUrl="~/work/bianpaimanage/manage1-1.aspx" Target="main" Text="各参赛项目分组"
                            Value="各参赛项目分组"></asp:TreeNode>
                        <asp:TreeNode NavigateUrl="~/work/search/search9.aspx" Target="main" Text="查询各项目分组情况"
                            Value="查询各项目分组情况"></asp:TreeNode>
                        <asp:TreeNode Text="生成运动会秩序册" Value="生成运动会秩序册" NavigateUrl="~/work/bianpaimanage/zhixuce.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode NavigateUrl="~/work/search/search9.aspx" Target="main" Text="检录单分组打印"
                            Value="检录单分组打印"></asp:TreeNode>
                        <asp:TreeNode Text="运动员各兼项比赛时间" Value="运动员各兼项比赛时间" NavigateUrl="#" Target="main"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="赛况管理" Value="赛况管理">
                        <asp:TreeNode Text="比赛成绩录入" Value="比赛成绩录入" NavigateUrl="~/saikuangmanage/scoremanage.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="比赛成绩查询" Value="比赛成绩查询" NavigateUrl="~/saikuangmanage/showscore.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="平破纪录统计表" Value="平破纪录统计表" NavigateUrl="#" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="团体积分统计表" Value="团体积分统计表" NavigateUrl="#" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="生成成绩册" Value="生成成绩册" Target="main" NavigateUrl="#"></asp:TreeNode>
                        <asp:TreeNode Text="运动员各兼项比赛成绩" Value="运动员各兼项比赛成绩" Target="main" NavigateUrl="#"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="维护" Value="维护">
                        <asp:TreeNode NavigateUrl="System/user_add.aspx" Target="main" Text="添加用户" Value="添加用户">
                        </asp:TreeNode>
                        <asp:TreeNode NavigateUrl="System/user_manage.aspx" Target="main" Text="用户管理" Value="用户管理">
                        </asp:TreeNode>
                        <asp:TreeNode Text="数据库备份" Value="数据库备份" Target="main" NavigateUrl="~/System/savedata.aspx"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="帮助" Value="帮助">
                        <asp:TreeNode Text="帮助主题" Value="帮助主题" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="关于运动会编排系统" Value="关于运动会编排系统" Target="main"></asp:TreeNode>
                    </asp:TreeNode>
                  
                </Nodes>
                <RootNodeStyle Font-Bold="True" Font-Size="14px" />
            </asp:TreeView><asp:TreeView ID="TreeView2" runat="server" Font-Size="Small" Width="139px" AutoGenerateDataBindings="False" EnableTheming="True" ExpandDepth="0">
                <Nodes>
                    <asp:TreeNode Text="查询统计" Value="查询统计">
                        <asp:TreeNode Text="参赛规程查询" Value="参赛规程查询" NavigateUrl="~/work/search/search1.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="运动员情况统计" Value="运动员情况统计" Target="main" NavigateUrl="~/work/search/search0.aspx"></asp:TreeNode>
                        <asp:TreeNode Text="参赛项目统计" Value="参赛项目统计" NavigateUrl="~/work/search/search4.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="参赛队基本信息统计" Value="参赛队基本信息统计" Target="main" NavigateUrl="~/work/search/search5.aspx"></asp:TreeNode>
                        <asp:TreeNode Text="运动员参赛情况统计" Value="运动员参赛情况统计" Target="main" NavigateUrl="~/work/search/search6.aspx"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="赛况管理" Value="赛况管理">
                        <asp:TreeNode Text="比赛成绩录入" Value="比赛成绩录入" NavigateUrl="~/saikuangmanage/scoremanage.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="比赛成绩查询" Value="比赛成绩查询" NavigateUrl="~/saikuangmanage/showscore.aspx" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="平破纪录统计表" Value="平破纪录统计表" NavigateUrl="#" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="团体积分统计表" Value="团体积分统计表" NavigateUrl="#" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="生成成绩册" Value="生成成绩册" Target="main" NavigateUrl="#"></asp:TreeNode>
                        <asp:TreeNode Text="运动员各兼项比赛成绩" Value="运动员各兼项比赛成绩" Target="main" NavigateUrl="#"></asp:TreeNode>
                    </asp:TreeNode>
                    <asp:TreeNode Text="帮助" Value="帮助">
                        <asp:TreeNode Text="帮助主题" Value="帮助主题" Target="main"></asp:TreeNode>
                        <asp:TreeNode Text="关于运动会编排系统" Value="关于运动会编排系统" Target="main"></asp:TreeNode>
                    </asp:TreeNode>
                </Nodes>
                <RootNodeStyle Font-Bold="True" Font-Size="14px" />
            </asp:TreeView>
    </TD>
	</TR>
	<TR>
		<TD COLSPAN=3 style="height: 7px"> 
			<IMG SRC="images/default_8.gif" WIDTH=1024 HEIGHT=8 ></TD>
	</TR>
</TABLE>
   		
    </div>
    </form>
</body>
</html>
